### ISSUE TITLE
ROADMAP 2025

### ISSUE THREAD

**Issue by kuwisdelu** [kuwisdelu/Cardinal#57]
This issue serves as a __tentative__ outline of development planned for 2025.

IF YOU ARE A USER, DO NOT MAKE RESEARCH PLANS BASED ON THIS TIMELINE.

**Comment by kuwisdelu** [comment]
# Spring 2025

## Cardinal 3.10 (Bioconductor 3.21 - expected April)

This will be our 10th anniversary edition! We can be ambitious. Among other new features, this should finally be the release where we introduce a GUI.

- [ ] Graphical user interface
  + Based on __shiny__
  + Visualization only (for now)
  + Maybe preview pre-processing?
  + `iMSI()`? `MSIView()`? `msiView()`?
- [ ] Ion mobility (experimental)
  + Support for timsTOF via TIMSCONVERT to imzML
  + Add `readTIMSData()` function
  + Read mobility arrays with cvParam "MS:1003006"
  + Load data as `TIMSImagingExperiment`
  + Add `peakProcess()` method for `TIMSImagingExperiment`
  + Pre-release on Github in February/March?
- [ ] Co-registration (experimental)
  + Native support for simple linear and affine transformations
  + Add `coregister` method based on `matter::warp2_trans()`
  + Aim to be good enough for visualization, but not necessarily annotation
  + More advanced methods coming later in __CardinalNN__

## CardinalNN 0.99 (under development)

This will be our companion package for any neural network-based methods requiring Python.

- [ ] Prototype R package
- [ ] Define Basilisk virtual environments
- [ ] Methods for serializing core objects to Python
  + Need to figure out how to map to Python classes
  + May need to pull data into memory for `matter` -> `numpy.ndarray`
  + Eventually we'll want native `matter` objects in Python
- [ ] Bindings for __msireg__?
  + Need to coordinate with Sai
- [ ] Bindings for __mzclustering__?
  + Khoury Research Apprenticeship project

**Comment by kuwisdelu** [comment]
None of the above happened because US politics overwhelmed the author.

Let's try again.

# Spring 2026

## Cardinal 3.14 (Bioconductor 3.23 - expected April)

This update will be focused on usability and cleaning up the public API.

- [ ] Refactor core classes
  + Decouple `MSImagingArrays` and `MSImagingExperiment`
  + Use `MSImagingArrays` for processing spectra
  + Use `MSImagingExperiment` for downstream analysis
- [ ] Refactor spectral processing
  + Harmonize processing function implementations
  + Refactor `process()`
  + Refactor `peakProcess()`
  + Remove unnecessary generic functions
- [ ] Refactor results storage
- [ ] Refactor imzML import/export
- [ ] Refactor `pixels()` and `features()`

## CardinalStats (under development)

Statistical learning methods will be moved to a new package.

- [ ] Prototype CardinalStats package
- [ ] Implement nearest neighbor methods (BiocNeighbors)
- [ ] Implement dimension reduction methods (BiocSingular)
- [ ] Implement clustering methods (bluster)
